export type ProgramCategory =
  | "Tax credits"
  | "Cash assistance"
  | "Food"
  | "Healthcare"
  | "Housing & utilities"
  | "Child care & family"
  | "Education & training"
  | "Veterans & military"
  | "Seniors & disability"
  | "Disaster & legal"
  | "Unclaimed money"
  | "Grants for organizations";

export type Program = {
  id: string;
  name: string;
  agency: string;
  category: ProgramCategory;
  estimate: string;
  summary: string;
  who: string;
};

export const CATEGORIES = [
  { key: "Tax credits", blurb: "Refundable credits and unfiled returns that often add up to thousands." },
  { key: "Cash assistance", blurb: "Direct payments, emergency funds, and income support." },
  { key: "Food", blurb: "Monthly grocery support for households, kids, and seniors." },
  { key: "Healthcare", blurb: "Free or low-cost coverage, prescriptions, and care programs." },
  { key: "Housing & utilities", blurb: "Rent support, energy bills, repairs, and emergency assistance." },
  { key: "Child care & family", blurb: "Child care vouchers, pre-K, and support for parents." },
  { key: "Education & training", blurb: "Grants, work-study, loan relief, and job training." },
  { key: "Veterans & military", blurb: "Benefits earned through military service." },
  { key: "Seniors & disability", blurb: "Support for older adults and people with disabilities." },
  { key: "Disaster & legal", blurb: "Disaster relief, crime victim funds, and free legal help." },
  { key: "Unclaimed money", blurb: "Money already in your name sitting with an agency." },
  { key: "Grants for organizations", blurb: "Funding for nonprofits, small businesses, and local agencies." },
] as const;

export const PROGRAMS: Program[] = [
  {
    id: "eitc",
    name: "Earned Income Tax Credit (EITC)",
    agency: "IRS",
    category: "Tax credits",
    estimate: "Up to ~$7,830",
    summary: "A refundable credit for working people with low to moderate income.",
    who: "Workers with earned income; amount scales with children in the household.",
  },
  {
    id: "ctc",
    name: "Child Tax Credit (CTC)",
    agency: "IRS",
    category: "Tax credits",
    estimate: "Up to $2,000 per child",
    summary: "Per-child credit that can lower your tax bill or come back as a refund.",
    who: "Parents and guardians of qualifying children under 17.",
  },
  {
    id: "actc",
    name: "Additional Child Tax Credit",
    agency: "IRS",
    category: "Tax credits",
    estimate: "Up to $1,700 per child",
    summary: "The refundable portion of the Child Tax Credit paid out as cash.",
    who: "Families whose CTC is larger than the tax they owe.",
  },
  {
    id: "cdcc",
    name: "Child & Dependent Care Credit",
    agency: "IRS",
    category: "Tax credits",
    estimate: "Up to 35% of expenses",
    summary: "Credit for work-related child or dependent care costs.",
    who: "Working parents or caregivers paying for care.",
  },
  {
    id: "aotc",
    name: "American Opportunity Tax Credit",
    agency: "IRS",
    category: "Tax credits",
    estimate: "Up to $2,500",
    summary: "Credit for tuition, fees, and course materials in the first four years of college.",
    who: "Undergraduate students or whoever claims them.",
  },
  {
    id: "llc",
    name: "Lifetime Learning Credit",
    agency: "IRS",
    category: "Tax credits",
    estimate: "Up to $2,000",
    summary: "Credit for tuition at any level, including part-time and job-skills courses.",
    who: "Students of any age taking eligible courses.",
  },
  {
    id: "ptc",
    name: "Premium Tax Credit",
    agency: "IRS",
    category: "Tax credits",
    estimate: "Varies monthly",
    summary: "Cuts the price of a Marketplace health plan, sometimes to near zero.",
    who: "People buying their own health insurance.",
  },
  {
    id: "savers-credit",
    name: "Saver's Credit",
    agency: "IRS",
    category: "Tax credits",
    estimate: "Up to $1,000 ($2,000 joint)",
    summary: "Credit for money you put into a retirement account.",
    who: "Low- and moderate-income savers.",
  },
  {
    id: "adoption-credit",
    name: "Adoption Tax Credit",
    agency: "IRS",
    category: "Tax credits",
    estimate: "Up to ~$16,800",
    summary: "Credit for qualified adoption expenses.",
    who: "Families who adopted a child.",
  },
  {
    id: "ev-credit",
    name: "Clean Vehicle Credit",
    agency: "IRS",
    category: "Tax credits",
    estimate: "Up to $7,500",
    summary: "Credit for buying a qualifying new or used electric vehicle.",
    who: "Buyers under the income caps.",
  },
  {
    id: "energy-home-credit",
    name: "Energy Efficient Home Improvement Credit",
    agency: "IRS",
    category: "Tax credits",
    estimate: "Up to $3,200/year",
    summary: "Credit for insulation, heat pumps, windows, and efficiency upgrades.",
    who: "Homeowners making qualifying improvements.",
  },
  {
    id: "solar-credit",
    name: "Residential Clean Energy Credit",
    agency: "IRS",
    category: "Tax credits",
    estimate: "30% of cost",
    summary: "Credit for solar, wind, geothermal, and battery storage at home.",
    who: "Homeowners installing clean energy systems.",
  },
  {
    id: "back-refunds",
    name: "Unfiled prior-year refunds",
    agency: "IRS",
    category: "Tax credits",
    estimate: "Varies",
    summary: "Refunds from past years you never claimed are still collectable for a window.",
    who: "Anyone who skipped filing while owed money.",
  },
  {
    id: "state-eitc",
    name: "State Earned Income Credits",
    agency: "State tax agencies",
    category: "Tax credits",
    estimate: "10–40% of federal EITC",
    summary: "Many states add their own match on top of the federal EITC.",
    who: "EITC-eligible filers in participating states.",
  },
  {
    id: "property-tax-relief",
    name: "Property tax & renter credits",
    agency: "State tax agencies",
    category: "Tax credits",
    estimate: "$200–$1,500",
    summary: "State circuit-breaker credits that refund part of rent or property tax.",
    who: "Renters and homeowners under state income limits.",
  },
  {
    id: "elderly-disabled-credit",
    name: "Credit for the Elderly or Disabled",
    agency: "IRS",
    category: "Tax credits",
    estimate: "$3,750–$7,500",
    summary: "A credit for older adults and people on permanent disability.",
    who: "Filers 65+ or retired on total disability with limited income.",
  },
  {
    id: "tanf",
    name: "Temporary Assistance for Needy Families (TANF)",
    agency: "HHS / state agencies",
    category: "Cash assistance",
    estimate: "$200–$700/month",
    summary: "Time-limited cash assistance for low-income families with children.",
    who: "Parents and caretakers under state income limits.",
  },
  {
    id: "ssi",
    name: "Supplemental Security Income (SSI)",
    agency: "Social Security Administration",
    category: "Cash assistance",
    estimate: "Up to ~$967/month",
    summary: "Monthly cash for people who are 65+, blind, or disabled with very limited income.",
    who: "Individuals with minimal income and resources.",
  },
  {
    id: "ssdi",
    name: "Social Security Disability Insurance (SSDI)",
    agency: "Social Security Administration",
    category: "Cash assistance",
    estimate: "Varies by work record",
    summary: "Monthly benefit when a disability keeps you from substantial work.",
    who: "Workers with enough recent work credits.",
  },
  {
    id: "ss-retirement",
    name: "Social Security Retirement Benefits",
    agency: "Social Security Administration",
    category: "Cash assistance",
    estimate: "Varies by earnings",
    summary: "Monthly payments based on your lifetime earnings.",
    who: "Workers 62 and older who paid into the system.",
  },
  {
    id: "ss-survivor",
    name: "Social Security Survivor Benefits",
    agency: "Social Security Administration",
    category: "Cash assistance",
    estimate: "Varies",
    summary: "Monthly payments to the family of a worker who died.",
    who: "Spouses, children, and dependent parents.",
  },
  {
    id: "ss-family",
    name: "Social Security Family Benefits",
    agency: "Social Security Administration",
    category: "Cash assistance",
    estimate: "Up to 50% of worker benefit",
    summary: "Payments to family members of someone on retirement or disability benefits.",
    who: "Spouses and children of an entitled worker.",
  },
  {
    id: "general-assistance",
    name: "General Assistance (GA)",
    agency: "County governments",
    category: "Cash assistance",
    estimate: "$100–$400/month",
    summary: "Small, short-term cash help where the state offers it.",
    who: "Adults without dependent children who don't qualify elsewhere.",
  },
  {
    id: "ui",
    name: "Unemployment Insurance (UI)",
    agency: "DOL / state agencies",
    category: "Cash assistance",
    estimate: "40–60% of prior wages",
    summary: "Temporary income after losing a job through no fault of your own.",
    who: "Recently employed workers who meet state rules.",
  },
  {
    id: "dua",
    name: "Disaster Unemployment Assistance",
    agency: "DOL / FEMA",
    category: "Cash assistance",
    estimate: "Varies weekly",
    summary: "Unemployment pay for people whose work stopped because of a declared disaster.",
    who: "Workers and self-employed in disaster areas.",
  },
  {
    id: "fema-ia",
    name: "FEMA Individual Assistance",
    agency: "FEMA",
    category: "Cash assistance",
    estimate: "Varies by need",
    summary: "Grants for disaster-caused expenses insurance won't cover.",
    who: "Households in federally declared disaster areas.",
  },
  {
    id: "eip-recovery",
    name: "Recovery Rebate Credit",
    agency: "IRS",
    category: "Cash assistance",
    estimate: "Up to $1,400",
    summary: "Stimulus payments you never received, claimed on a return.",
    who: "Filers who missed one of the economic impact payments.",
  },
  {
    id: "child-support",
    name: "Child support enforcement",
    agency: "HHS / state agencies",
    category: "Cash assistance",
    estimate: "Varies",
    summary: "Free help locating a parent and collecting owed support.",
    who: "Custodial parents owed child support.",
  },
  {
    id: "emergency-assistance",
    name: "Emergency cash assistance funds",
    agency: "State & county agencies",
    category: "Cash assistance",
    estimate: "One-time $200–$1,500",
    summary: "One-time payments for a crisis: eviction, utility shutoff, or car repair.",
    who: "Households facing a documented emergency.",
  },
  {
    id: "snap",
    name: "SNAP food benefits",
    agency: "USDA / state agencies",
    category: "Food",
    estimate: "~$200+/month",
    summary: "A monthly grocery balance loaded onto an EBT card.",
    who: "Households under the income limit for their size.",
  },
  {
    id: "wic",
    name: "WIC",
    agency: "USDA / state agencies",
    category: "Food",
    estimate: "~$70/month + food package",
    summary: "Nutrition support for pregnant people, infants, and children under five.",
    who: "Families with young children who meet income guidelines.",
  },
  {
    id: "school-meals",
    name: "Free & reduced school meals",
    agency: "USDA",
    category: "Food",
    estimate: "~$1,000/child per year",
    summary: "Daily breakfast and lunch at no cost during the school year.",
    who: "School-age children in qualifying households.",
  },
  {
    id: "summer-ebt",
    name: "Summer EBT (SUN Bucks)",
    agency: "USDA",
    category: "Food",
    estimate: "$120 per child per summer",
    summary: "Grocery money for kids while school is out.",
    who: "Children eligible for free or reduced-price meals.",
  },
  {
    id: "csfp",
    name: "Commodity Supplemental Food Program",
    agency: "USDA",
    category: "Food",
    estimate: "Monthly food box",
    summary: "A monthly box of staple groceries for older adults.",
    who: "Adults 60+ under income limits.",
  },
  {
    id: "tefap",
    name: "Emergency Food Assistance (TEFAP)",
    agency: "USDA",
    category: "Food",
    estimate: "Free groceries",
    summary: "USDA food distributed through local pantries.",
    who: "Anyone under local income guidelines.",
  },
  {
    id: "snap-ed",
    name: "Double Up Food Bucks / SNAP incentives",
    agency: "USDA & nonprofits",
    category: "Food",
    estimate: "Match up to $20–$40/visit",
    summary: "Doubles SNAP dollars spent on fruits and vegetables.",
    who: "SNAP shoppers at participating markets.",
  },
  {
    id: "senior-farmers-market",
    name: "Senior Farmers' Market Nutrition Program",
    agency: "USDA",
    category: "Food",
    estimate: "$50/season",
    summary: "Vouchers for fresh produce at farmers markets.",
    who: "Low-income adults 60+.",
  },
  {
    id: "wic-farmers-market",
    name: "WIC Farmers' Market Nutrition Program",
    agency: "USDA",
    category: "Food",
    estimate: "$30/season",
    summary: "Produce vouchers added to WIC benefits.",
    who: "WIC participants in participating states.",
  },
  {
    id: "meals-on-wheels",
    name: "Home-delivered & congregate meals",
    agency: "Administration for Community Living",
    category: "Food",
    estimate: "Free or donation",
    summary: "Delivered meals and community dining for older adults.",
    who: "Adults 60+, especially homebound seniors.",
  },
  {
    id: "cacfp",
    name: "Child & Adult Care Food Program",
    agency: "USDA",
    category: "Food",
    estimate: "Free meals",
    summary: "Meals and snacks at child care centers and adult day programs.",
    who: "Children and adults in participating care settings.",
  },
  {
    id: "food-pantries",
    name: "Local food pantry network",
    agency: "Feeding America & local groups",
    category: "Food",
    estimate: "Free groceries",
    summary: "Weekly or monthly groceries with little or no paperwork.",
    who: "Anyone in need; income rules vary by pantry.",
  },
  {
    id: "medicaid",
    name: "Medicaid",
    agency: "CMS / state agencies",
    category: "Healthcare",
    estimate: "Full coverage",
    summary: "Comprehensive health coverage with little or no monthly premium.",
    who: "Adults and families under state income thresholds.",
  },
  {
    id: "chip",
    name: "CHIP",
    agency: "CMS / state agencies",
    category: "Healthcare",
    estimate: "Low or no cost",
    summary: "Children's coverage for families who earn too much for Medicaid.",
    who: "Households with kids and modest income.",
  },
  {
    id: "marketplace",
    name: "Marketplace premium credits",
    agency: "HealthCare.gov",
    category: "Healthcare",
    estimate: "Varies monthly",
    summary: "Subsidies that cut the price of a private plan, sometimes to near zero.",
    who: "People without job-based coverage.",
  },
  {
    id: "csr",
    name: "Cost-sharing reductions",
    agency: "HealthCare.gov",
    category: "Healthcare",
    estimate: "Lower deductibles & copays",
    summary: "Extra savings on out-of-pocket costs with a Silver Marketplace plan.",
    who: "Enrollees under 250% of the poverty line.",
  },
  {
    id: "medicare-savings",
    name: "Medicare Savings Programs",
    agency: "CMS / state agencies",
    category: "Healthcare",
    estimate: "Pays Part B premium (~$185/mo)",
    summary: "State programs that pay Medicare premiums and sometimes copays.",
    who: "Medicare enrollees with limited income.",
  },
  {
    id: "extra-help",
    name: "Medicare Extra Help (Part D LIS)",
    agency: "Social Security Administration",
    category: "Healthcare",
    estimate: "~$5,900/year value",
    summary: "Cuts prescription drug costs to a few dollars per fill.",
    who: "Medicare enrollees under the income and asset limits.",
  },
  {
    id: "medicaid-expansion",
    name: "Adult Medicaid expansion coverage",
    agency: "CMS / state agencies",
    category: "Healthcare",
    estimate: "Full coverage",
    summary: "Coverage for adults up to 138% of the poverty line in expansion states.",
    who: "Adults 19–64 in participating states.",
  },
  {
    id: "chc",
    name: "Community Health Centers (FQHCs)",
    agency: "HRSA",
    category: "Healthcare",
    estimate: "Sliding-scale fees",
    summary: "Primary, dental, and behavioral care priced to your income.",
    who: "Anyone, insured or not.",
  },
  {
    id: "hill-burton",
    name: "Hospital charity care",
    agency: "Hospitals / HHS",
    category: "Healthcare",
    estimate: "Bills reduced or erased",
    summary: "Nonprofit hospitals must discount or forgive bills for qualifying patients.",
    who: "Patients under the hospital's income policy.",
  },
  {
    id: "vfc",
    name: "Vaccines for Children",
    agency: "CDC",
    category: "Healthcare",
    estimate: "Free vaccines",
    summary: "No-cost childhood immunizations.",
    who: "Uninsured, Medicaid, or underinsured children.",
  },
  {
    id: "ryan-white",
    name: "Ryan White HIV/AIDS Program",
    agency: "HRSA",
    category: "Healthcare",
    estimate: "Free care & medication",
    summary: "Medical care, medication, and support for people with HIV.",
    who: "Low-income people living with HIV.",
  },
  {
    id: "family-planning",
    name: "Title X family planning",
    agency: "HHS",
    category: "Healthcare",
    estimate: "Free or sliding scale",
    summary: "Contraception, screenings, and reproductive care.",
    who: "Anyone; priority to low-income patients.",
  },
  {
    id: "adap",
    name: "AIDS Drug Assistance Program",
    agency: "HRSA / states",
    category: "Healthcare",
    estimate: "Free medication",
    summary: "Covers HIV medications for people who can't afford them.",
    who: "Low-income people living with HIV.",
  },
  {
    id: "mat-sud",
    name: "Substance use & mental health block grant services",
    agency: "SAMHSA",
    category: "Healthcare",
    estimate: "Free or sliding scale",
    summary: "Treatment, counseling, and recovery support at local providers.",
    who: "People seeking treatment; income rules vary.",
  },
  {
    id: "prescription-assistance",
    name: "Patient assistance programs",
    agency: "Drug manufacturers",
    category: "Healthcare",
    estimate: "Free or discounted drugs",
    summary: "Manufacturer programs that supply medication at no cost.",
    who: "Uninsured or underinsured patients.",
  },
  {
    id: "bccp",
    name: "Breast & Cervical Cancer Early Detection",
    agency: "CDC",
    category: "Healthcare",
    estimate: "Free screening",
    summary: "Free mammograms and Pap tests, plus treatment coverage if needed.",
    who: "Uninsured women under income limits.",
  },
  {
    id: "section8",
    name: "Housing Choice Vouchers (Section 8)",
    agency: "HUD / local PHAs",
    category: "Housing & utilities",
    estimate: "Rent capped near 30% of income",
    summary: "A voucher that pays part of your rent to a private landlord.",
    who: "Renters under local income limits; waitlists apply.",
  },
  {
    id: "public-housing",
    name: "Public housing",
    agency: "HUD / local PHAs",
    category: "Housing & utilities",
    estimate: "Rent near 30% of income",
    summary: "Apartments owned and managed by a housing authority.",
    who: "Low-income families, seniors, and people with disabilities.",
  },
  {
    id: "liheap",
    name: "Energy bill assistance (LIHEAP)",
    agency: "HHS / state agencies",
    category: "Housing & utilities",
    estimate: "$300–$1,000/year",
    summary: "Help with heating, cooling, and past-due utility balances.",
    who: "Households facing high energy costs or shutoff notices.",
  },
  {
    id: "lihwap",
    name: "Water bill assistance (LIHWAP)",
    agency: "HHS / state agencies",
    category: "Housing & utilities",
    estimate: "$200–$1,000",
    summary: "Help with overdue water and wastewater bills.",
    who: "Households at risk of water shutoff.",
  },
  {
    id: "wap",
    name: "Weatherization Assistance Program",
    agency: "DOE / state agencies",
    category: "Housing & utilities",
    estimate: "~$8,000 in upgrades",
    summary: "Free insulation, sealing, and heating repairs to cut energy bills.",
    who: "Low-income homeowners and renters.",
  },
  {
    id: "acp-lifeline",
    name: "Lifeline phone & internet discount",
    agency: "FCC",
    category: "Housing & utilities",
    estimate: "Up to $9.25/month",
    summary: "A monthly discount on phone or broadband service.",
    who: "Households on SNAP, Medicaid, SSI, or under income limits.",
  },
  {
    id: "section202",
    name: "Section 202 Supportive Housing for the Elderly",
    agency: "HUD",
    category: "Housing & utilities",
    estimate: "Rent near 30% of income",
    summary: "Subsidized apartments with services for older adults.",
    who: "Very low-income adults 62+.",
  },
  {
    id: "section811",
    name: "Section 811 Housing for Persons with Disabilities",
    agency: "HUD",
    category: "Housing & utilities",
    estimate: "Rent near 30% of income",
    summary: "Accessible, subsidized housing with support services.",
    who: "Very low-income adults with disabilities.",
  },
  {
    id: "usda-502",
    name: "USDA Single Family Housing Loans & Grants",
    agency: "USDA Rural Development",
    category: "Housing & utilities",
    estimate: "0% loans, up to $10,000 grants",
    summary: "Home purchase loans and repair grants in rural areas.",
    who: "Rural households under income limits.",
  },
  {
    id: "hud-hoc",
    name: "HUD-approved housing counseling",
    agency: "HUD",
    category: "Housing & utilities",
    estimate: "Free counseling",
    summary: "Free help with rent, mortgages, foreclosure, and homebuying.",
    who: "Anyone, at no cost.",
  },
  {
    id: "hafa-hardship",
    name: "Homeowner Assistance Fund",
    agency: "Treasury / states",
    category: "Housing & utilities",
    estimate: "Up to $40,000",
    summary: "Mortgage, tax, and utility help for homeowners after a hardship.",
    who: "Homeowners behind on payments where funds remain.",
  },
  {
    id: "era",
    name: "Emergency rental assistance",
    agency: "Treasury / local agencies",
    category: "Housing & utilities",
    estimate: "Back rent + utilities",
    summary: "Pays overdue rent and utility bills to prevent eviction.",
    who: "Renters with a hardship where local funds remain.",
  },
  {
    id: "continuum-of-care",
    name: "Homelessness assistance (Continuum of Care)",
    agency: "HUD",
    category: "Housing & utilities",
    estimate: "Housing + services",
    summary: "Rapid rehousing, transitional housing, and permanent supportive housing.",
    who: "People experiencing or at risk of homelessness.",
  },
  {
    id: "hud-vash",
    name: "HUD-VASH",
    agency: "HUD & VA",
    category: "Housing & utilities",
    estimate: "Voucher + case management",
    summary: "Housing vouchers paired with VA services for veterans.",
    who: "Veterans experiencing homelessness.",
  },
  {
    id: "solar-for-all",
    name: "Low-income solar & community solar credits",
    agency: "EPA / states",
    category: "Housing & utilities",
    estimate: "10–20% off power bills",
    summary: "Discounted community solar subscriptions and rooftop programs.",
    who: "Income-qualified households in participating states.",
  },
  {
    id: "home-repair-grants",
    name: "Home repair & accessibility grants",
    agency: "USDA / local agencies",
    category: "Housing & utilities",
    estimate: "$5,000–$10,000",
    summary: "Grants for roofs, ramps, and safety repairs.",
    who: "Older or disabled homeowners under income limits.",
  },
  {
    id: "project-based-rental-assistance",
    name: "Project-Based Rental Assistance (Section 8 PBRA)",
    agency: "HUD",
    category: "Housing & utilities",
    estimate: "Rent near 30% of income",
    summary: "Subsidy tied to a specific apartment building instead of a portable voucher.",
    who: "Low-income renters applying directly to participating properties.",
  },
  {
    id: "lihtc-apartments",
    name: "Low-Income Housing Tax Credit apartments",
    agency: "IRS / state housing agencies",
    category: "Housing & utilities",
    estimate: "Below-market rent",
    summary: "Privately owned apartments with rents capped for income-qualified tenants.",
    who: "Households under 50–60% of area median income.",
  },
  {
    id: "fss",
    name: "Family Self-Sufficiency (FSS) escrow",
    agency: "HUD / local PHAs",
    category: "Housing & utilities",
    estimate: "$5,000–$10,000 savings payout",
    summary: "As your earnings rise, the rent increase is banked into an escrow account you keep.",
    who: "Voucher and public housing residents who enroll.",
  },
  {
    id: "housing-choice-homeownership",
    name: "Housing Choice Voucher homeownership option",
    agency: "HUD / local PHAs",
    category: "Housing & utilities",
    estimate: "Voucher applied to mortgage",
    summary: "Use your rental voucher toward monthly mortgage payments instead of rent.",
    who: "First-time buyers with a voucher in participating PHAs.",
  },
  {
    id: "fha-loans",
    name: "FHA-insured home loans",
    agency: "HUD / FHA",
    category: "Housing & utilities",
    estimate: "3.5% down payment",
    summary: "Government-insured mortgages with lower credit and down-payment requirements.",
    who: "Buyers who can't qualify for conventional financing.",
  },
  {
    id: "dpa-programs",
    name: "Down payment & closing cost assistance",
    agency: "State & local housing finance agencies",
    category: "Housing & utilities",
    estimate: "$5,000–$25,000",
    summary: "Grants or forgivable second loans that cover down payment and closing costs.",
    who: "First-time buyers under program income limits.",
  },
  {
    id: "mcc",
    name: "Mortgage Credit Certificate (MCC)",
    agency: "State housing finance agencies",
    category: "Housing & utilities",
    estimate: "Up to $2,000/year tax credit",
    summary: "Converts part of your mortgage interest into a yearly federal tax credit.",
    who: "First-time buyers who get the certificate at closing.",
  },
  {
    id: "usda-504",
    name: "USDA Section 504 repair loans & grants",
    agency: "USDA Rural Development",
    category: "Housing & utilities",
    estimate: "1% loans up to $40,000; $10,000 grants",
    summary: "Repair and modernize a rural home, or remove health and safety hazards.",
    who: "Very low-income rural homeowners; grants for owners 62+.",
  },
  {
    id: "home-program",
    name: "HOME Investment Partnerships",
    agency: "HUD / local governments",
    category: "Housing & utilities",
    estimate: "Rent or purchase help",
    summary: "Local rehab, rental, and homebuyer programs funded by HUD block grants.",
    who: "Low-income renters and buyers in participating cities and counties.",
  },
  {
    id: "cdbg-housing",
    name: "Community Development Block Grant housing help",
    agency: "HUD / local governments",
    category: "Housing & utilities",
    estimate: "Varies by locality",
    summary: "City and county rehab, accessibility, and emergency housing programs.",
    who: "Low- and moderate-income residents of the funded area.",
  },
  {
    id: "esg",
    name: "Emergency Solutions Grants (shelter & rehousing)",
    agency: "HUD / local agencies",
    category: "Housing & utilities",
    estimate: "Shelter + short-term rent",
    summary: "Emergency shelter, street outreach, and short-term rehousing payments.",
    who: "People who are homeless or facing imminent eviction.",
  },
  {
    id: "vawa-housing",
    name: "Housing protections & transfers for survivors (VAWA)",
    agency: "HUD",
    category: "Housing & utilities",
    estimate: "Emergency transfer + protection",
    summary: "Protection from eviction and an emergency move to safe assisted housing.",
    who: "Survivors of domestic violence, dating violence, or stalking.",
  },
  {
    id: "fair-housing-complaint",
    name: "Fair housing discrimination complaints",
    agency: "HUD Office of Fair Housing",
    category: "Housing & utilities",
    estimate: "Free investigation",
    summary: "Free investigation and possible damages when you're denied housing unlawfully.",
    who: "Anyone discriminated against based on a protected class.",
  },
  {
    id: "tribal-housing",
    name: "Indian Housing Block Grant & Section 184 loans",
    agency: "HUD Office of Native American Programs",
    category: "Housing & utilities",
    estimate: "Rent help; 2.25% down loans",
    summary: "Tribal rental assistance, rehab, and low-down-payment home loans.",
    who: "Members of federally recognized tribes and Alaska Native villages.",
  },
  {
    id: "farm-labor-housing",
    name: "Farm Labor Housing loans & rental help",
    agency: "USDA Rural Development",
    category: "Housing & utilities",
    estimate: "Rent near 30% of income",
    summary: "Affordable housing built and subsidized for farmworker families.",
    who: "Domestic farm laborers and their households.",
  },
  {
    id: "lead-hazard-grants",
    name: "Lead hazard control & healthy homes grants",
    agency: "HUD",
    category: "Housing & utilities",
    estimate: "Free remediation",
    summary: "Removes lead paint, mold, and other hazards from older homes.",
    who: "Low-income households with children in pre-1978 housing.",
  },
  {
    id: "energy-efficiency-rebates",
    name: "Home energy rebates (HEAR & HOMES)",
    agency: "DOE / state energy offices",
    category: "Housing & utilities",
    estimate: "Up to $14,000",
    summary: "Rebates for heat pumps, wiring, insulation, and efficient appliances.",
    who: "Households under 150% of area median income in launched states.",
  },
  {
    id: "utility-shutoff-protection",
    name: "Utility shutoff protection & arrears forgiveness",
    agency: "State public utility commissions",
    category: "Housing & utilities",
    estimate: "Debt forgiveness + fixed bills",
    summary: "Seasonal shutoff bans, budget billing, and forgiveness of past-due balances.",
    who: "Customers on low incomes or with a medical hardship.",
  },
  {
    id: "eviction-legal-help",
    name: "Eviction prevention & tenant legal aid",
    agency: "Local courts & legal aid",
    category: "Housing & utilities",
    estimate: "Free representation",
    summary: "Free attorneys, mediation, and rent funds to stop an eviction filing.",
    who: "Tenants facing eviction in participating cities and states.",
  },
  {
    id: "ccdf",
    name: "Child Care & Development Fund (CCDF)",
    agency: "HHS / state agencies",
    category: "Child care & family",
    estimate: "Most of your child care bill",
    summary: "Vouchers that cover child care so you can work or study.",
    who: "Working or studying parents under state income limits.",
  },
  {
    id: "head-start",
    name: "Head Start / Early Head Start",
    agency: "HHS",
    category: "Child care & family",
    estimate: "Free program",
    summary: "Free early education, health, and family support from birth to age 5.",
    who: "Low-income families with young children.",
  },
  {
    id: "state-prek",
    name: "State-funded Pre-K",
    agency: "State education departments",
    category: "Child care & family",
    estimate: "Free or low cost",
    summary: "Public pre-kindergarten for 3- and 4-year-olds.",
    who: "Families in states and districts that offer it.",
  },
  {
    id: "home-visiting",
    name: "Maternal & child home visiting (MIECHV)",
    agency: "HRSA",
    category: "Child care & family",
    estimate: "Free",
    summary: "Nurse and parent-coach visits during pregnancy and early childhood.",
    who: "Pregnant people and families with infants.",
  },
  {
    id: "cps-diaper",
    name: "Diaper and formula banks",
    agency: "Nonprofits & state pilots",
    category: "Child care & family",
    estimate: "Free supplies",
    summary: "Free diapers, wipes, and formula from local banks.",
    who: "Families with infants and toddlers.",
  },
  {
    id: "foster-adoption-assist",
    name: "Foster care & adoption assistance",
    agency: "HHS / state agencies",
    category: "Child care & family",
    estimate: "Monthly stipend",
    summary: "Monthly support for foster and adoptive parents.",
    who: "Licensed foster and adoptive families.",
  },
  {
    id: "child-care-tax-fsa",
    name: "Dependent Care FSA",
    agency: "IRS / employers",
    category: "Child care & family",
    estimate: "Up to $5,000 pre-tax",
    summary: "Set aside pre-tax pay for child or dependent care.",
    who: "Employees whose job offers the benefit.",
  },
  {
    id: "wic-breastfeeding",
    name: "WIC breastfeeding peer support",
    agency: "USDA",
    category: "Child care & family",
    estimate: "Free support & pumps",
    summary: "Counseling and breast pumps for nursing parents.",
    who: "WIC participants.",
  },
  {
    id: "pell",
    name: "Federal Pell Grant",
    agency: "Dept. of Education",
    category: "Education & training",
    estimate: "Up to ~$7,395/year",
    summary: "A grant for undergraduates with high financial need - no repayment.",
    who: "Undergraduates who file the FAFSA.",
  },
  {
    id: "fseog",
    name: "Federal Supplemental Educational Opportunity Grant",
    agency: "Dept. of Education",
    category: "Education & training",
    estimate: "$100–$4,000/year",
    summary: "Extra grant aid for the highest-need students.",
    who: "Pell-eligible students at participating schools.",
  },
  {
    id: "work-study",
    name: "Federal Work-Study",
    agency: "Dept. of Education",
    category: "Education & training",
    estimate: "Part-time wages",
    summary: "Part-time campus or community jobs funded by financial aid.",
    who: "Students with demonstrated need.",
  },
  {
    id: "teach-grant",
    name: "TEACH Grant",
    agency: "Dept. of Education",
    category: "Education & training",
    estimate: "Up to $4,000/year",
    summary: "Grants for future teachers who commit to high-need schools.",
    who: "Education students meeting the service agreement.",
  },
  {
    id: "pslf",
    name: "Public Service Loan Forgiveness",
    agency: "Dept. of Education",
    category: "Education & training",
    estimate: "Remaining balance erased",
    summary: "Loan forgiveness after 120 payments in public service work.",
    who: "Government and nonprofit employees.",
  },
  {
    id: "idr",
    name: "Income-driven repayment & forgiveness",
    agency: "Dept. of Education",
    category: "Education & training",
    estimate: "Payments as low as $0",
    summary: "Caps student loan payments at a share of your income.",
    who: "Federal student loan borrowers.",
  },
  {
    id: "wioa",
    name: "WIOA job training grants",
    agency: "DOL / state agencies",
    category: "Education & training",
    estimate: "Free training",
    summary: "Paid-for training, certifications, and job placement help.",
    who: "Adults, youth, and dislocated workers.",
  },
  {
    id: "job-corps",
    name: "Job Corps",
    agency: "DOL",
    category: "Education & training",
    estimate: "Free training + housing",
    summary: "Free career training, housing, and a stipend for young adults.",
    who: "People 16–24 who meet income rules.",
  },
  {
    id: "apprenticeship",
    name: "Registered Apprenticeships",
    agency: "DOL",
    category: "Education & training",
    estimate: "Paid training",
    summary: "Earn a wage while learning a trade, with no tuition.",
    who: "Anyone accepted into a registered program.",
  },
  {
    id: "state-tuition-free",
    name: "State tuition-free college promise programs",
    agency: "State agencies",
    category: "Education & training",
    estimate: "Tuition covered",
    summary: "Community college or university tuition covered by the state.",
    who: "Residents meeting state program rules.",
  },
  {
    id: "ged-adult-ed",
    name: "Adult education & GED programs",
    agency: "Dept. of Education / states",
    category: "Education & training",
    estimate: "Free classes",
    summary: "Free literacy, GED, and English-language classes.",
    who: "Adults without a high school diploma.",
  },
  {
    id: "americorps",
    name: "AmeriCorps education award",
    agency: "AmeriCorps",
    category: "Education & training",
    estimate: "~$7,395 award + stipend",
    summary: "Service year with a living allowance and a college award.",
    who: "Adults accepted into a service position.",
  },
  {
    id: "va-disability",
    name: "VA Disability Compensation",
    agency: "VA",
    category: "Veterans & military",
    estimate: "$175–$4,000+/month",
    summary: "Tax-free monthly pay for service-connected conditions.",
    who: "Veterans with a rated disability.",
  },
  {
    id: "va-pension",
    name: "VA Veterans Pension",
    agency: "VA",
    category: "Veterans & military",
    estimate: "Up to ~$1,800/month",
    summary: "Monthly income for low-income wartime veterans 65+ or disabled.",
    who: "Wartime veterans under income limits.",
  },
  {
    id: "va-aid-attendance",
    name: "VA Aid & Attendance",
    agency: "VA",
    category: "Veterans & military",
    estimate: "Added to pension",
    summary: "Extra monthly money for veterans who need daily care.",
    who: "Pension-eligible veterans needing assistance.",
  },
  {
    id: "va-healthcare",
    name: "VA Health Care",
    agency: "VA",
    category: "Veterans & military",
    estimate: "Free or low copays",
    summary: "Comprehensive medical care through VA facilities.",
    who: "Enrolled veterans by priority group.",
  },
  {
    id: "gi-bill",
    name: "Post-9/11 GI Bill",
    agency: "VA",
    category: "Veterans & military",
    estimate: "Tuition + housing stipend",
    summary: "Pays tuition and a monthly housing allowance for school.",
    who: "Veterans with qualifying service.",
  },
  {
    id: "vr-e",
    name: "Veteran Readiness & Employment (Chapter 31)",
    agency: "VA",
    category: "Veterans & military",
    estimate: "Training + stipend",
    summary: "Retraining and job placement for veterans with service-connected disabilities.",
    who: "Veterans with a qualifying rating.",
  },
  {
    id: "dic",
    name: "Dependency & Indemnity Compensation",
    agency: "VA",
    category: "Veterans & military",
    estimate: "~$1,600+/month",
    summary: "Monthly payment to survivors of service members and veterans.",
    who: "Surviving spouses, children, and parents.",
  },
  {
    id: "va-home-loan",
    name: "VA Home Loan Guaranty",
    agency: "VA",
    category: "Veterans & military",
    estimate: "$0 down payment",
    summary: "No-down-payment mortgages with no private mortgage insurance.",
    who: "Veterans, service members, and some spouses.",
  },
  {
    id: "sah-grant",
    name: "Specially Adapted Housing grants",
    agency: "VA",
    category: "Veterans & military",
    estimate: "Up to ~$117,000",
    summary: "Grants to build or modify an accessible home.",
    who: "Veterans with qualifying service-connected disabilities.",
  },
  {
    id: "ltss-waivers",
    name: "Medicaid Home & Community-Based waivers",
    agency: "CMS / state agencies",
    category: "Seniors & disability",
    estimate: "Care at home covered",
    summary: "Pays for in-home aides and services instead of a nursing home.",
    who: "People needing a nursing-home level of care.",
  },
  {
    id: "pace",
    name: "PACE (All-Inclusive Care for the Elderly)",
    agency: "CMS",
    category: "Seniors & disability",
    estimate: "Full care coverage",
    summary: "All-in-one medical and daily care so you can stay at home.",
    who: "Adults 55+ needing nursing-home level care.",
  },
  {
    id: "ship",
    name: "State Health Insurance Assistance Program (SHIP)",
    agency: "ACL",
    category: "Seniors & disability",
    estimate: "Free counseling",
    summary: "Free one-on-one Medicare counseling.",
    who: "Medicare beneficiaries and families.",
  },
  {
    id: "aaa-services",
    name: "Area Agency on Aging services",
    agency: "ACL",
    category: "Seniors & disability",
    estimate: "Free or donation",
    summary: "Transportation, chore help, and caregiver respite for older adults.",
    who: "Adults 60+ and their caregivers.",
  },
  {
    id: "scsep",
    name: "Senior Community Service Employment Program",
    agency: "DOL",
    category: "Seniors & disability",
    estimate: "Paid training",
    summary: "Paid part-time community jobs and training for older workers.",
    who: "Job seekers 55+ under income limits.",
  },
  {
    id: "ticket-to-work",
    name: "Ticket to Work",
    agency: "Social Security Administration",
    category: "Seniors & disability",
    estimate: "Free services",
    summary: "Free career support while keeping disability benefits during the transition.",
    who: "SSI and SSDI recipients 18–64.",
  },
  {
    id: "able-accounts",
    name: "ABLE savings accounts",
    agency: "Treasury / states",
    category: "Seniors & disability",
    estimate: "Tax-free savings",
    summary: "Save without losing SSI or Medicaid eligibility.",
    who: "People whose disability began before age 26.",
  },
  {
    id: "assistive-tech",
    name: "State assistive technology programs",
    agency: "ACL",
    category: "Seniors & disability",
    estimate: "Free loans & low-interest financing",
    summary: "Device loans, reuse programs, and financing for assistive tech.",
    who: "People with disabilities of any age.",
  },
  {
    id: "caregiver-support",
    name: "National Family Caregiver Support Program",
    agency: "ACL",
    category: "Seniors & disability",
    estimate: "Respite & training",
    summary: "Respite care, counseling, and training for unpaid caregivers.",
    who: "Family caregivers of older adults.",
  },
  {
    id: "sba-disaster",
    name: "SBA Disaster Loans",
    agency: "Small Business Administration",
    category: "Disaster & legal",
    estimate: "Up to $500,000",
    summary: "Low-interest loans to repair homes, property, and businesses.",
    who: "Homeowners, renters, and businesses in disaster areas.",
  },
  {
    id: "crime-victim-comp",
    name: "Crime Victim Compensation",
    agency: "DOJ / state boards",
    category: "Disaster & legal",
    estimate: "Up to $25,000",
    summary: "Reimburses medical bills, counseling, and lost wages after a crime.",
    who: "Victims of violent crime and their families.",
  },
  {
    id: "lsc-legal-aid",
    name: "Free civil legal aid",
    agency: "Legal Services Corporation",
    category: "Disaster & legal",
    estimate: "Free representation",
    summary: "Free lawyers for eviction, benefits appeals, and family cases.",
    who: "Households under 125% of the poverty line.",
  },
  {
    id: "taxpayer-clinics",
    name: "Low Income Taxpayer Clinics",
    agency: "IRS",
    category: "Disaster & legal",
    estimate: "Free representation",
    summary: "Free help disputing IRS bills, audits, and back taxes.",
    who: "Taxpayers under income limits.",
  },
  {
    id: "disaster-snap",
    name: "Disaster SNAP (D-SNAP)",
    agency: "USDA",
    category: "Disaster & legal",
    estimate: "One month of benefits",
    summary: "Emergency food benefits after a declared disaster.",
    who: "Households affected by a disaster, even if not usually eligible.",
  },
  {
    id: "fema-flood",
    name: "Increased Cost of Compliance (flood)",
    agency: "FEMA",
    category: "Disaster & legal",
    estimate: "Up to $30,000",
    summary: "Helps pay to elevate or floodproof a damaged home.",
    who: "NFIP policyholders with major flood damage.",
  },
  {
    id: "state-unclaimed",
    name: "State unclaimed property",
    agency: "State treasurers",
    category: "Unclaimed money",
    estimate: "Average $1,000+",
    summary: "Forgotten deposits, refunds, and paychecks held by your state.",
    who: "Anyone who has moved or changed banks or jobs.",
  },
  {
    id: "pension-search",
    name: "Unclaimed pensions",
    agency: "Pension Benefit Guaranty Corp.",
    category: "Unclaimed money",
    estimate: "Varies",
    summary: "Pension benefits from employers that closed or were taken over.",
    who: "Former employees of terminated plans.",
  },
  {
    id: "savings-bonds",
    name: "Matured savings bonds",
    agency: "Treasury",
    category: "Unclaimed money",
    estimate: "Face value + interest",
    summary: "Bonds that stopped earning interest and were never cashed.",
    who: "Bond holders and their heirs.",
  },
  {
    id: "fha-refunds",
    name: "FHA mortgage insurance refunds",
    agency: "HUD",
    category: "Unclaimed money",
    estimate: "$500–$1,500",
    summary: "Refunds of upfront mortgage insurance after an early payoff.",
    who: "Former FHA borrowers.",
  },
  {
    id: "class-action",
    name: "Class action settlement funds",
    agency: "Courts & administrators",
    category: "Unclaimed money",
    estimate: "$10–$1,000+",
    summary: "Settlement payouts you may qualify for as a past customer.",
    who: "Consumers included in a settlement class.",
  },
  {
    id: "tax-overpayment",
    name: "Uncashed IRS refund checks",
    agency: "IRS",
    category: "Unclaimed money",
    estimate: "Varies",
    summary: "Refund checks that were returned, lost, or never deposited.",
    who: "Filers who moved or changed banks.",
  },
  {
    id: "cdbg",
    name: "Community Development Block Grant (CDBG)",
    agency: "HUD",
    category: "Grants for organizations",
    estimate: "Varies by award",
    summary: "Flexible funding for community development and services.",
    who: "State and local governments, nonprofits.",
  },
  {
    id: "nih-grants",
    name: "NIH Research Grants",
    agency: "National Institutes of Health",
    category: "Grants for organizations",
    estimate: "Varies by award",
    summary: "Funding for biomedical and health research.",
    who: "Universities and research institutions.",
  },
  {
    id: "ars-grants",
    name: "USDA Agricultural Research grants",
    agency: "USDA ARS",
    category: "Grants for organizations",
    estimate: "Varies by award",
    summary: "Funding for agricultural research and innovation.",
    who: "Universities and agricultural organizations.",
  },
  {
    id: "epa-grants",
    name: "EPA Environmental grants",
    agency: "EPA",
    category: "Grants for organizations",
    estimate: "Varies by award",
    summary: "Funding for environmental protection and cleanup projects.",
    who: "Governments, tribes, and nonprofits.",
  },
  {
    id: "shsgp",
    name: "State Homeland Security Grant Program",
    agency: "DHS",
    category: "Grants for organizations",
    estimate: "Varies by award",
    summary: "Preparedness funding for state and local agencies.",
    who: "State, local, and tribal governments.",
  },
  {
    id: "sbir",
    name: "Small Business Innovation Research (SBIR)",
    agency: "SBA & agencies",
    category: "Grants for organizations",
    estimate: "$50,000–$1M+",
    summary: "R&D funding for small businesses commercializing technology.",
    who: "Small businesses meeting SBA standards.",
  },
  {
    id: "worc",
    name: "Workforce Opportunity for Rural Communities (WORC)",
    agency: "DOL",
    category: "Grants for organizations",
    estimate: "Varies by award",
    summary: "Grants for workforce development in rural regions.",
    who: "Workforce boards and nonprofits.",
  },
  {
    id: "teach-inst",
    name: "TEACH Grant program (institutional)",
    agency: "Dept. of Education",
    category: "Grants for organizations",
    estimate: "Varies by award",
    summary: "Institutional participation in the TEACH grant program.",
    who: "Eligible educational institutions.",
  },
];
